### ISSUE TITLE
TypeError: 'int' object is not subscriptable. It happens in sfd_head.py when build network.

### ISSUE THREAD

**Issue by Raiden-cn** [LittlePey/SFD#4]
Finnally,I can train this code in 30 series card with above Issues !
but there still are some questions.

In sfd_head.py , there is a code follows:

            for k in range(len(mlps)):
                mlps[k] = [input_channels[src_name]] + mlps[k]

input_chennels is a int not a List,I have no idea which config get wrong.

TypeError: 'int' object is not subscriptable

Thanks for your reply.

**Comment by WWW2323** [comment]
Hi, it seems that you add our method to a new version of OpenPCDet? You may need to use backbone_channels instead of input_channels. You can refer to [lin9](https://github.com/open-mmlab/OpenPCDet/blob/dadda9ed5c0f190d06856c6ec15d552116203947/pcdet/models/roi_heads/voxelrcnn_head.py#L9) and [line22](https://github.com/open-mmlab/OpenPCDet/blob/dadda9ed5c0f190d06856c6ec15d552116203947/pcdet/models/roi_heads/voxelrcnn_head.py#L22).

**Comment by LittlePey** [comment]
Hi, it seems that you add our method to a new version of OpenPCDet? You may need to use backbone_channels instead of input_channels. You can refer to [lin9](https://github.com/open-mmlab/OpenPCDet/blob/dadda9ed5c0f190d06856c6ec15d552116203947/pcdet/models/roi_heads/voxelrcnn_head.py#L9) and [line22](https://github.com/open-mmlab/OpenPCDet/blob/dadda9ed5c0f190d06856c6ec15d552116203947/pcdet/models/roi_heads/voxelrcnn_head.py#L22).
